language: objective-c
osx_image: xcode7.3
env:
  matrix:
  - VERSION=8.4
  - VERSION=latest
cache:
  bundler: true
  directories:
    - vendor/bundle
    - Pods
before_install:
  - export LANG=en_US.UTF-8
install:
  - bundle install --without development --deployment --jobs=3 --retry=3
  - bundle exec pod install --no-repo-update
script:
  - xcodebuild -project ICInputAccessory.xcodeproj -scheme ICInputAccessory-iOS -sdk iphonesimulator -destination "name=iPhone 6,OS=$VERSION" clean build | xcpretty -c
  - xcodebuild -workspace ICInputAccessory.xcworkspace -scheme Example -sdk iphonesimulator -destination "name=iPhone 6,OS=$VERSION" clean test | xcpretty -c
notifications:
  email: false
